default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV.fetch('RAILS_APP_DATABASE_USER', 'root') %>
  password: <%= ENV.fetch('RAILS_APP_DATABASE_PASSWORD', 'Aa@123456') %>
  host: <%= ENV.fetch('DATABASE_HOSTNAME', 'localhost') %>
  database: <%= ENV.fetch('RAILS_APP_DATABASE_NAME', 'rails_react_blog') %>
  reconnect: true

development:
  <<: *default
  database: <%= ENV.fetch('RAILS_APP_DATABASE_NAME', 'rails_react_blog_development') %>

test:
  <<: *default
  database: rails_react_blog_test

production:
  <<: *default
  pool: 32
  host: <%= ENV.fetch('DATABASE_HOSTNAME', 'app_sv_production') %>
  database: <%= ENV.fetch('RAILS_APP_DATABASE_NAME', 'rails_app_production') %>
  username: <%= ENV['RAILS_APP_DATABASE_USER'] %>
  password: <%= ENV['RAILS_APP_DATABASE_PASSWORD'] %>

staging:
  <<: *default
